remote_theme: sighingnow/jekyll-gitbook
author: Tan Pike
title: TanBlog
description: Tan sez stuff

collections:
  pages:
    output: true
    
toc:
    enabled: true
    h_min: 1
    h_max: 3
